### ISSUE TITLE
Error: Unable to Create evance_net network 

### ISSUE THREAD

**Issue by uzaxirr** [ameerthehacker/envase#12]
Suddenly this error popped out of nowhere.
PS: _I did some major changes with docker 2 days before this, like removing unnecessary images and clusters etc etc._

OS: Elementry OS (based on Ubuuntu 18.04)
 
![Screenshot from 2021-12-31 11 18 01](https://user-images.githubusercontent.com/72073401/147805998-56742de9-00e1-4bc0-ba38-58fce5479c22.png)

**Comment by ameerthehacker** [comment]
@uzaxirr 
run the bellow command
```
docker network ls
```

If you see `envase_net` in it then 

```
docker network rm envase_net
```

else 

```
docker network create envase_net
```

**Comment by uzaxirr** [comment]
> @uzaxirr run the bellow command
> 
> ```
> docker network ls
> ```
> 
> If you see `envase_net` in it then
> 
> ```
> docker network rm envase_net
> ```
> 
> else
> 
> ```
> docker network create envase_net
> ```

Thanks, it solved it. There were two networks with name as `envase_net` which was causing the problem. Removed one of them
![Screenshot from 2021-12-31 13-31-22](https://user-images.githubusercontent.com/72073401/147811110-7051f7d8-5561-4783-a2fb-6cdab103855d.png)
